#include "daemon/XjcdRender.hh"

#include "file/CleanerConfig.hh"
#include "file/PolicyConfig.hh"

#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <unistd.h>

namespace JournalCache {
namespace {

std::string readFileIfExists(const std::string &path) {
  std::ifstream in(path);
  if (!in) {
    return {};
  }
  std::ostringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

void replaceAll(std::string &text, const std::string &from,
                const std::string &to) {
  if (from.empty()) {
    return;
  }
  size_t pos = 0;
  while ((pos = text.find(from, pos)) != std::string::npos) {
    text.replace(pos, from.size(), to);
    pos += to.size();
  }
}

std::string xrootdTemplate() {
  return R"(# Generated by xjcd — JournalCache forwarding cache proxy
all.sitename JournalCache@{{hostname}}

port {{xroot_port}}
port tls {{https_port}}

xrd.protocol http:{{lib_dir}}/libXrdHttp.so

http.cert {{tls_cert}}
http.key {{tls_key}}

pss.origin =root,http,https
all.export /
ofs.osslib libXrdPss.so

http.header2cgi If-None-Match xrd.journalcache.if-none-match
http.header2cgi If-Modified-Since xrd.journalcache.if-modified-since

http.exthandler journalcache libXrdClJournalCacheHttpExt-{{plugin_suffix}}.so \
  {{http_ext_conf}}

xrootd.chksum max 2 md5 adler32 crc32 crc32c
)";
}

std::string httpExtTemplate() {
  return R"(# Generated by xjcd — JournalCache HTTP ext (forwarding proxy mode)
forwarding = 1

cache = {{journal}}/
flat = 0
basepath =

prefix = /
exclude = /static/

policy = {{policy_path}}
policy_poll = 2

# allow_origin / external_redirect: edit {{policy_path}} with xjc
)";
}

std::string clientPluginTemplate() {
  return R"(# Generated by xjcd — client plugins for the xrootd/PSS process
url = *
lib = libXrdClJournalCachePlugin-{{plugin_suffix}}.so
enable = true
cache = {{journal}}/
stats = 60
policy = {{policy_path}}
policy_poll = 2
multi_origin = 1

url = http*
lib = libXrdClHttp.so
enable = true

url = https*
lib = libXrdClHttp.so
enable = true
)";
}

std::string systemdEnvTemplate() {
  return R"(# Generated by xjcd — EnvironmentFile snippet for systemd
XRD_PLUGINCONFDIR={{client_plugin_dir}}
XRD_JOURNALCACHE_CACHE={{journal}}/
XRD_JOURNALCACHE_POLICY={{policy_path}}
XRD_JOURNALCACHE_CLEANER={{cleaner_path}}
)";
}

std::string cleanerSystemdEnvTemplate() {
  return R"(# Generated by xjcd — EnvironmentFile snippet for xjccleand
XRD_JOURNALCACHE_CACHE={{journal}}/
XRD_JOURNALCACHE_CLEANER={{cleaner_path}}
)";
}

std::string cleanerSystemdUnitTemplate() {
  return R"([Unit]
Description=JournalCache cache cleaner (xjccleand) on {{journal}}
Documentation=file:{{cleaner_path}}
After=network-online.target local-fs.target remote-fs.target time-sync.target
Wants=network-online.target local-fs.target remote-fs.target time-sync.target
RequiresMountsFor={{journal}}

[Service]
Type=simple
User=xrootd
Group=xrootd
Environment="TZ=:/etc/localtime"
EnvironmentFile=-{{cleaner_systemd_env}}
ExecStart=/usr/bin/xjccleand --journal {{journal}}
KillMode=control-group
Restart=on-abnormal
RestartSec=10
UMask=0027

LockPersonality=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=full
RemoveIPC=true
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
)";
}

std::string systemdUnitTemplate() {
  return R"([Unit]
Description=JournalCache forwarding proxy (xjcd) on {{journal}}
Documentation=file:{{xrootd_conf}}
After=network-online.target local-fs.target remote-fs.target time-sync.target
Wants=network-online.target local-fs.target remote-fs.target time-sync.target
RequiresMountsFor={{journal}}

[Service]
Type=simple
User=xrootd
Group=xrootd
Environment="TZ=:/etc/localtime"
EnvironmentFile=-{{systemd_env}}
ExecStart=/usr/bin/xrootd -c {{xrootd_conf}} -R daemon
KillMode=control-group
LimitNOFILE=524288
Restart=on-abnormal
RestartSec=10
UMask=0027

AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
LockPersonality=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=full
RemoveIPC=true
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
)";
}

std::string systemdUnitHint(const XjcdState &state) {
  std::ostringstream out;
  out << "# Install the generated units:\n"
      << "#   sudo install -m 0644 " << state.systemdUnitPath()
      << " /etc/systemd/system/\n"
      << "#   sudo install -m 0644 " << state.cleanerSystemdUnitPath()
      << " /etc/systemd/system/\n"
      << "#   sudo systemctl daemon-reload\n"
      << "#   sudo systemctl enable --now xjcd.service xjccleand.service\n";
  return out.str();
}

} // namespace

std::string substituteTemplate(const std::string &tmpl, const XjcdState &state,
                               const std::string &hostname) {
  std::string out = tmpl;
  replaceAll(out, "{{hostname}}", hostname);
  replaceAll(out, "{{journal}}", state.journal);
  replaceAll(out, "{{xroot_port}}", std::to_string(state.xrootPort));
  replaceAll(out, "{{https_port}}", std::to_string(state.httpsPort));
  replaceAll(out, "{{tls_cert}}", state.tlsCert);
  replaceAll(out, "{{tls_key}}", state.tlsKey);
  replaceAll(out, "{{lib_dir}}", state.libDir);
  replaceAll(out, "{{plugin_suffix}}", state.pluginSuffix);
  replaceAll(out, "{{policy_path}}", state.policyPath());
  replaceAll(out, "{{http_ext_conf}}", state.httpExtConfigPath());
  replaceAll(out, "{{client_plugin_dir}}", state.clientPluginDir());
  replaceAll(out, "{{xrootd_conf}}", state.xrootdConfigPath());
  replaceAll(out, "{{systemd_env}}", state.systemdEnvPath());
  replaceAll(out, "{{cleaner_path}}", state.cleanerPath());
  replaceAll(out, "{{cleaner_systemd_env}}", state.cleanerSystemdEnvPath());
  return out;
}

bool writeTextFile(const std::string &path, const std::string &content) {
  const std::string tmp = path + ".tmp";
  {
    std::ofstream out(tmp, std::ios::trunc);
    if (!out) {
      return false;
    }
    out << content;
    if (!out) {
      return false;
    }
  }
  std::error_code ec;
  std::filesystem::rename(tmp, path, ec);
  if (ec) {
    std::filesystem::remove(tmp, ec);
    return false;
  }
  return true;
}

bool ensureInitialPolicy(const std::string &policyPath) {
  if (readFileIfExists(policyPath).empty()) {
    PolicySettings settings;
    settings.bypass = false;
    settings.multiOriginUnwrap = true;
    return savePolicyFile(policyPath, settings);
  }
  return true;
}

bool ensureInitialCleaner(const XjcdState &state) {
  const std::string path = state.cleanerPath();
  if (readFileIfExists(path).empty()) {
    CleanerSettings settings;
    settings.journal = state.journal;
    settings.highWatermark = 10ull * 1024ull * 1024ull * 1024ull;
    settings.lowWatermark = 0;
    settings.interval = 60;
    settings.configPoll = 2;
    return saveCleanerFile(path, settings);
  }
  return true;
}

bool renderXjcdConfigs(const XjcdState &state, const std::string &hostname) {
  std::error_code ec;
  std::filesystem::create_directories(state.clientPluginDir(), ec);
  std::filesystem::create_directories(state.journal, ec);

  if (!ensureInitialPolicy(state.policyPath())) {
    return false;
  }
  if (!ensureInitialCleaner(state)) {
    return false;
  }

  const std::string xrootd =
      substituteTemplate(xrootdTemplate(), state, hostname);
  const std::string httpExt =
      substituteTemplate(httpExtTemplate(), state, hostname);
  const std::string clientPlugin =
      substituteTemplate(clientPluginTemplate(), state, hostname);
  const std::string env =
      substituteTemplate(systemdEnvTemplate(), state, hostname);
  const std::string unit =
      substituteTemplate(systemdUnitTemplate(), state, hostname);
  const std::string cleanerEnv =
      substituteTemplate(cleanerSystemdEnvTemplate(), state, hostname);
  const std::string cleanerUnit =
      substituteTemplate(cleanerSystemdUnitTemplate(), state, hostname);

  if (!writeTextFile(state.xrootdConfigPath(), xrootd) ||
      !writeTextFile(state.httpExtConfigPath(), httpExt) ||
      !writeTextFile(state.clientPluginConfigPath(), clientPlugin) ||
      !writeTextFile(state.systemdEnvPath(), env) ||
      !writeTextFile(state.systemdUnitPath(), unit) ||
      !writeTextFile(state.cleanerSystemdEnvPath(), cleanerEnv) ||
      !writeTextFile(state.cleanerSystemdUnitPath(), cleanerUnit)) {
    return false;
  }

  const std::string readme = systemdUnitHint(state) +
                             "\n# Runtime policy (xjc):\n#   " +
                             state.policyPath() +
                             "\n# Cleaner config (xjc cleaner):\n#   " +
                             state.cleanerPath() + "\n";
  return writeTextFile(state.etcDir() + "/README.systemd.txt", readme);
}

std::string defaultSystemdUnitName() { return "xjcd.service"; }

std::string defaultCleanerSystemdUnitName() { return "xjccleand.service"; }

std::string systemdUnitInstallPath(const std::string &unitName) {
  return "/etc/systemd/system/" + unitName;
}

bool isValidSystemdUnitName(const std::string &unitName) {
  if (unitName.size() < 9 || unitName.compare(unitName.size() - 8, 8, ".service") != 0) {
    return false;
  }
  for (const char ch : unitName) {
    const unsigned char uch = static_cast<unsigned char>(ch);
    if (std::isalnum(uch) || ch == '-' || ch == '_' || ch == '.' || ch == '@') {
      continue;
    }
    return false;
  }
  return unitName.find('/') == std::string::npos;
}

bool installSystemdUnitFile(const std::string &sourceUnitPath,
                            const std::string &unitName, std::string &error) {
  if (!isValidSystemdUnitName(unitName)) {
    error = "invalid systemd unit name: " + unitName;
    return false;
  }
  if (!std::filesystem::exists(sourceUnitPath)) {
    error = "generated unit not found: " + sourceUnitPath;
    return false;
  }

  const std::string dest = systemdUnitInstallPath(unitName);
  std::error_code ec;
  std::filesystem::copy_file(sourceUnitPath, dest,
                             std::filesystem::copy_options::overwrite_existing,
                             ec);
  if (ec) {
    error = "failed to install unit to " + dest + ": " + ec.message();
    return false;
  }
  std::filesystem::permissions(
      dest,
      std::filesystem::perms::owner_read | std::filesystem::perms::group_read |
          std::filesystem::perms::others_read,
      ec);
  if (ec) {
    error = "failed to set permissions on " + dest + ": " + ec.message();
    return false;
  }
  return true;
}

bool installXjcdSystemdUnit(const XjcdState &state, const std::string &unitName,
                            bool enable, std::string &error) {
  return installXjcdSystemdUnits(state, unitName,
                                 defaultCleanerSystemdUnitName(), enable,
                                 error);
}

bool installXjcdSystemdUnits(const XjcdState &state,
                             const std::string &proxyUnitName,
                             const std::string &cleanerUnitName, bool enable,
                             std::string &error) {
  if (geteuid() != 0) {
    error = "--install-systemd requires root; re-run with sudo";
    return false;
  }
  if (!installSystemdUnitFile(state.systemdUnitPath(), proxyUnitName, error)) {
    return false;
  }
  if (!installSystemdUnitFile(state.cleanerSystemdUnitPath(), cleanerUnitName,
                              error)) {
    return false;
  }
  if (std::system("systemctl daemon-reload") != 0) {
    error = "systemctl daemon-reload failed";
    return false;
  }
  if (enable) {
    const std::string cmd =
        "systemctl enable --now " + proxyUnitName + " " + cleanerUnitName;
    if (std::system(cmd.c_str()) != 0) {
      error = "systemctl enable --now failed for " + proxyUnitName + " and " +
              cleanerUnitName;
      return false;
    }
  }
  return true;
}

std::vector<XjcdValidationIssue> validateXjcdState(const XjcdState &state) {
  std::vector<XjcdValidationIssue> issues;
  auto addError = [&](const std::string &msg) {
    issues.push_back({true, msg});
  };
  auto addWarn = [&](const std::string &msg) {
    issues.push_back({false, msg});
  };

  if (!state.isComplete()) {
    addError("state is incomplete; run xjcd init first");
    return issues;
  }

  if (state.xrootPort == 0 || state.xrootPort > 65535) {
    addError("invalid xroot_port");
  }
  if (state.httpsPort == 0 || state.httpsPort > 65535) {
    addError("invalid https_port");
  }

  std::error_code ec;
  if (!std::filesystem::exists(state.tlsCert)) {
    addError("tls cert not found: " + state.tlsCert);
  } else if (access(state.tlsCert.c_str(), R_OK) != 0) {
    addError("tls cert not readable: " + state.tlsCert);
  }
  if (!std::filesystem::exists(state.tlsKey)) {
    addError("tls key not found: " + state.tlsKey);
  } else if (access(state.tlsKey.c_str(), R_OK) != 0) {
    addError("tls key not readable: " + state.tlsKey);
  }

  if (!std::filesystem::exists(state.journal)) {
    addWarn("journal directory does not exist yet: " + state.journal);
  }

  const auto checkLib = [&](const std::string &name) {
    const std::string path = state.libDir + "/" + name;
    if (!std::filesystem::exists(path)) {
      addWarn("plugin library not found: " + path);
    }
  };
  checkLib("libXrdClJournalCachePlugin-" + state.pluginSuffix + ".so");
  checkLib("libXrdClJournalCacheHttpExt-" + state.pluginSuffix + ".so");
  checkLib("libXrdClHttp.so");
  checkLib("libXrdHttp.so");
  checkLib("libXrdPss.so");

  return issues;
}

} // namespace JournalCache
