//
// Created by segransm on //.
//

#ifndef XROOTD_XRDSACTION_HH
#define XROOTD_XRDSACTION_HH

namespace S3 {

enum class Action {
  Unknown,
  AbortMultipartUpload,
  CompleteMultipartUpload,
  CopyObject,
  CreateBucket,
  CreateMultipartUpload,
  DeleteBucket,
  DeleteBucketAnalyticsConfiguration,
  DeleteBucketCors,
  DeleteBucketEncryption,
  DeleteBucketIntelligentTieringConfiguration,
  DeleteBucketInventoryConfiguration,
  DeleteBucketLifecycle,
  DeleteBucketMetricsConfiguration,
  DeleteBucketOwnershipControls,
  DeleteBucketPolicy,
  DeleteBucketReplication,
  DeleteBucketTagging,
  DeleteBucketWebsite,
  DeleteObject,
  DeleteObjects,
  DeleteObjectTagging,
  DeletePublicAccessBlock,
  GetBucketAccelerateConfiguration,
  GetBucketAcl,
  GetBucketAnalyticsConfiguration,
  GetBucketCors,
  GetBucketEncryption,
  GetBucketIntelligentTieringConfiguration,
  GetBucketInventoryConfiguration,
  GetBucketLifecycleConfiguration,
  GetBucketLocation,
  GetBucketLogging,
  GetBucketMetricsConfiguration,
  GetBucketNotificationConfiguration,
  GetBucketOwnershipControls,
  GetBucketPolicy,
  GetBucketPolicyStatus,
  GetBucketReplication,
  GetBucketRequestPayment,
  GetBucketTagging,
  GetBucketVersioning,
  GetBucketWebsite,
  GetObject,
  GetObjectAcl,
  GetObjectAttributes,
  GetObjectLegalHold,
  GetObjectLockConfiguration,
  GetObjectRetention,
  GetObjectTagging,
  GetObjectTorrent,
  GetPublicAccessBlock,
  HeadBucket,
  HeadObject,
  ListBucketAnalyticsConfigurations,
  ListBucketIntelligentTieringConfigurations,
  ListBucketInventoryConfigurations,
  ListBucketMetricsConfigurations,
  ListBuckets,
  ListMultipartUploads,
  ListObjects,
  ListObjectsV2,
  ListObjectVersions,
  ListParts,
  PutBucketAccelerateConfiguration,
  PutBucketAcl,
  PutBucketAnalyticsConfiguration,
  PutBucketCors,
  PutBucketEncryption,
  PutBucketIntelligentTieringConfiguration,
  PutBucketInventoryConfiguration,
  PutBucketLifecycle,
  PutBucketLifecycleConfiguration,
  PutBucketLogging,
  PutBucketMetricsConfiguration,
  PutBucketNotification,
  PutBucketNotificationConfiguration,
  PutBucketOwnershipControls,
  PutBucketPolicy,
  PutBucketReplication,
  PutBucketRequestPayment,
  PutBucketTagging,
  PutBucketVersioning,
  PutBucketWebsite,
  PutObject,
  PutObjectAcl,
  PutObjectLegalHold,
  PutObjectLockConfiguration,
  PutObjectRetention,
  PutObjectTagging,
  PutPublicAccessBlock,
  RestoreObject,
  SelectObjectContent,
  UploadPart,
  UploadPartCopy,
  WriteGetObjectResponse,
};

}  // namespace S

#endif  // XROOTD_XRDSACTION_HH
