# Client plugins for JournalCache HTTP forwarding proxy (xrootd process)
#
# Install as /etc/xrootd/client.plugins.d/journalcache-forwarding.conf

url = *
lib = libXrdClJournalCachePlugin-5.so
enable = true
cache = /var/tmp/journalcache/
stats = 60

url = http*
lib = libXrdClHttp.so
enable = true

url = https*
lib = libXrdClHttp.so
enable = true
